import {APP_NAME} from '../../utils/constants'

const CONTAINER_NAME = 'Dummy'

export const GET_DUMMY_API = `${APP_NAME}/${CONTAINER_NAME}/GET_DUMMY_API`
export const GET_DUMMY_API_SUCCESS = `${APP_NAME}/${CONTAINER_NAME}/GET_DUMMY_API_SUCCESS`
export const GET_DUMMY_API_FAILED = `${APP_NAME}/${CONTAINER_NAME}/GET_DUMMY_API_FAILED`
