import {APP_NAME} from '../../utils/constants'

const CONTAINER_NAME = 'Drawer'

export const GET_CHARACTER_DETAIL = `${APP_NAME}/${CONTAINER_NAME}/GET_CHARACTER_DETAIL`
export const GET_CHARACTER_DETAIL_SUCCESS = `${APP_NAME}/${CONTAINER_NAME}/GET_CHARACTER_DETAIL_SUCCESS`
export const GET_CHARACTER_DETAIL_FAILED = `${APP_NAME}/${CONTAINER_NAME}/GET_CHARACTER_DETAIL_FAILED`
