import { APP_NAME } from "../../utils/constants";

const CONTAINER_NAME = "App";

export const POST_SIGN_IN = `${APP_NAME}/${CONTAINER_NAME}/POST_SIGN_IN`;
export const POST_SIGN_IN_SUCCESS = `${APP_NAME}/${CONTAINER_NAME}/POST_SIGN_IN_SUCCESS`;
export const POST_SIGN_IN_FAILED = `${APP_NAME}/${CONTAINER_NAME}/POST_SIGN_IN_FAILED`;


export const POST_REGISTER = `${APP_NAME}/${CONTAINER_NAME}/POST_REGISTER`;
export const POST_REGISTER_SUCCESS = `${APP_NAME}/${CONTAINER_NAME}/POST_REGISTER_SUCCESS`;
export const POST_REGISTER_FAILED = `${APP_NAME}/${CONTAINER_NAME}/POST_REGISTER_FAILED`;


